backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "fr"

# Force le rechargement des fichiers sans cache
load_config_file: false

collections:
  - name: "settings"
    label: "⚙️ Paramètres"
    files:
      - name: "menu_visibility"
        label: "Visibilité des sections du menu"
        file: "src/content/settings/menu-visibility.yml"
        fields:
          - {label: "Afficher les Entrées", name: "show_entrees", widget: "boolean", default: true}
          - {label: "Afficher les Potages (hiver)", name: "show_potages", widget: "boolean", default: true, hint: "Désactiver en été"}
          - {label: "Afficher les Plats", name: "show_plats", widget: "boolean", default: true}
          - {label: "Afficher les Moules-Frites", name: "show_moules", widget: "boolean", default: false, hint: "Activer quand la section est prête"}
          - {label: "Afficher les Pizzas", name: "show_pizzas", widget: "boolean", default: true}
          - {label: "Afficher les Formules", name: "show_formules", widget: "boolean", default: true}
          - {label: "Afficher le Menu Enfant", name: "show_enfant", widget: "boolean", default: true}
          - {label: "Afficher les Desserts", name: "show_desserts", widget: "boolean", default: true}
          - {label: "Afficher les Glaces", name: "show_glaces", widget: "boolean", default: true}

      - name: "opening_hours"
        label: "Horaires d'ouverture"
        file: "src/content/settings/opening-hours.yml"
        fields:
          - label: "Lundi"
            name: "monday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: true}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

          - label: "Mardi"
            name: "tuesday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: false}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: false}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: false}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

          - label: "Mercredi"
            name: "wednesday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: true}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

          - label: "Jeudi"
            name: "thursday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: true}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

          - label: "Vendredi"
            name: "friday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: true}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

          - label: "Samedi"
            name: "saturday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: true}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

          - label: "Dimanche"
            name: "sunday"
            widget: "object"
            fields:
              - {label: "Ouvert", name: "enabled", widget: "boolean", default: true}
              - label: "Déjeuner"
                name: "lunch"
                widget: "object"
                fields:
                  - {label: "Service déjeuner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "12:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "14:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
              - label: "Dîner"
                name: "dinner"
                widget: "object"
                fields:
                  - {label: "Service dîner", name: "enabled", widget: "boolean", default: true}
                  - {label: "Ouverture", name: "start", widget: "string", default: "19:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}
                  - {label: "Fermeture", name: "end", widget: "string", default: "22:00", pattern: ['^[0-9]{2}:[0-9]{2}$', "Format: HH:MM"]}

  - name: "menu_entrees"
    label: "Menu - Entrées"
    folder: "src/content/menu/entrees"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_potages"
    label: "Menu - Potages"
    folder: "src/content/menu/potages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_plats"
    label: "Menu - Plats"
    folder: "src/content/menu/plats"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_moules"
    label: "Menu - Moules-Frites"
    folder: "src/content/menu/moules"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_pizzas"
    label: "Menu - Pizzas"
    folder: "src/content/menu/pizzas"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_formules"
    label: "Menu - Formules"
    folder: "src/content/menu/formules"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_enfant"
    label: "Menu - Menu Enfant"
    folder: "src/content/menu/enfant"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_desserts"
    label: "Menu - Desserts"
    folder: "src/content/menu/desserts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_glaces"
    label: "Menu - Glaces"
    folder: "src/content/menu/glaces"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "news"
    label: "Actualités"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
