backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  - name: "menu_entrees"
    label: "Menu - Entrées"
    folder: "src/content/menu/entrees"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_potages"
    label: "Menu - Potages"
    folder: "src/content/menu/potages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_plats"
    label: "Menu - Plats"
    folder: "src/content/menu/plats"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_moules"
    label: "Menu - Moules"
    folder: "src/content/menu/moules"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_pizzas"
    label: "Menu - Pizzas"
    folder: "src/content/menu/pizzas"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_formules"
    label: "Menu - Formules"
    folder: "src/content/menu/formules"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_enfant"
    label: "Menu - Menu Enfant"
    folder: "src/content/menu/enfant"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_desserts"
    label: "Menu - Desserts"
    folder: "src/content/menu/desserts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "menu_glaces"
    label: "Menu - Glaces"
    folder: "src/content/menu/glaces"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom (Français)", name: "name", widget: "string"}
      - {label: "Nom (Anglais)", name: "nameEn", widget: "string"}
      - {label: "Prix", name: "price", widget: "string", pattern: ['^[0-9]+,[0-9]{2}$', "Format: 12,50"]}
      - {label: "Description (Français)", name: "description", widget: "text", required: false}
      - {label: "Description (Anglais)", name: "descriptionEn", widget: "text", required: false}
      - {label: "Ingrédients (Français)", name: "ingredients", widget: "string", required: false}
      - {label: "Ingrédients (Anglais)", name: "ingredientsEn", widget: "string", required: false}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
      - {label: "Disponible", name: "available", widget: "boolean", default: true}

  - name: "news"
    label: "Actualités"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
